lib/screens/widget/side_menu.dart

Add key parameter to the SideMenu widget to improve its performance and
maintainability. This change ensures that the widget can be uniquely
identified and efficiently updated by the framework during rebuilds.
fix(side_menu): Use constant BorderSide in RoundedRectangleBorder
Use a constant BorderSide instance in the RoundedRectangleBorder
construction to optimize memory usage and improve code readability.
This change ensures that the BorderSide object is not unnecessarily
recreated on each build.

feat(side_menu): Add key parameter to SideMenu widget

---

lib/screens/next_exam_screen.dart

The name of the `NextExamPage` class has been changed to `NextExamsPage` to better reflect the page's purpose of displaying a list of upcoming exams.

🎨 Rename NextExamPage to NextExamsPage

---

lib/routes_manger.dart
lib/screens/login_form.dart
lib/tools/response_handler.dart

- Refactor the `LoginForm` widget to use `GetBuilder` for handling loading state
- Replace `NextExamPage` with `NextExamsPage` in the `Routes` class to match the actual screen name
- Remove unused imports and organize the imports in the `login_form.dart` file

✨ feat: Improve login screen and fix next exams page name

---

lib/routes_manger.dart

The `NextExamScreen` has been renamed to `NextExamsScreen` to better
reflect the screen's purpose, which is to display a list of upcoming
exams rather than a single exam.

✨ feat(routes): Rename NextExamScreen to NextExamsScreen

---

lib/main.dart

Improve the Hive initialization process by using `Future.wait()` to asynchronously
open the 'Token' and 'Profile' boxes in parallel, reducing the overall
initialization time.

✨ feat: Optimize Hive initialization in main

---

lib/bindings/binding.dart
lib/controllers/student_barcode_controller.dart
lib/models/student/student_res_model.dart
lib/models/student_barcode_in_exam_room/student_barcode_in_exam_room.dart
lib/models/student_seat/student_seat_res_model.dart
lib/screens/students_in_exam_room/students_in_exam_room_screen.dart
lib/screens/widget/next_exam_widget.dart
lib/services/students_in_exam_room_service.dart

This commit introduces the following changes to the `StudentsInExamRoomController` and related files:
1. Adds the `isLoading` state to track the loading state of the screen.
2. Retrieves the selected exam room and exam mission IDs from the `StudentsInExamRoomService` and uses them to fetch the students in the exam room.
3. Handles the response from the API call and updates the `studentBarcodeInExamRoom` model accordingly.
4. Adds error handling using the `AwesomeDialog` widget to display any errors that occur during the API call.
5. Adds the `onClose` method to the `StudentsInExamRoomController` to delete the selected exam room and exam mission IDs from the `StudentsInExamRoomService` when the screen is closed.
6. Updates the `StudentSeatNumberResModel` and `StudentResModel` models by …

✨ feat: Implement students in exam room functionality

---

lib/main.dart
lib/main_app.dart
lib/routes_manger.dart

This commit fixes the import paths for the binding class and removes
unused code from the `_MyAppState` class. The changes improve the overall
code organization and maintainability of the `main_app.dart` file.
The key changes include:
- Updating the import path for `bindings.dart` file
- Removing the unused `initState` method from `_MyAppState` class
- Updating the `initialBinding` parameter in `GetMaterialApp` to use the
`InitialBindings` class

🐛 fix(main_app): fix binding imports and remove unused code

---

lib/controllers/next_exam_controller.dart

Adds the ability to fetch the next exams by the proctor's ID instead of a hardcoded control mission ID. This change ensures that the controller can retrieve the appropriate exam data for the logged-in proctor, improving the user experience.
The key changes are:
- Introduce a `userId` variable to store the proctor's ID
- Change the `getAllExamMissionsByProctorId` method to use the `userId` variable in the API request
- Call the `getAllExamMissionsByProctorId` method in the `onInit` override to fetch the exam data on controller initialization

✨ feat(NextExamController): Fetch next exams by proctor ID

---

lib/screens/students_in_exam_room/students_in_exam_room_screen.dart

The changes made in this commit focus on the following improvements:
1. Removed the commented-out code that was displaying a flash message after a successful action, as it was not being used.
2. Changed the type of the `result` variable from `String?` to `dynamic` to handle different types of data returned from the navigation push operation.
These changes aim to clean up the codebase and improve the overall quality and maintainability of the `StudentsInExamRoomScreen` component.

🐛 fix(StudentsInExamRoomScreen): remove unused code and improve variable type

---

pubspec.lock

The changes in this commit update the `custom_theme` package version from
`2b5ccd30701279d46e86750aa1f22d41d828cefa` to
`94f428303639df065f54b7f00cc8e7e12c4caaa0`. This update is necessary to
incorporate the latest improvements and bug fixes in the custom theme
package.

🎨 feat(theme): update custom_theme package version

---

.firebaserc

Updates the production app name in the `.firebaserc` file
from `control-proctor-app-2025` to `staging-control-proctor-app-2025`.
This change is necessary to deploy the application to the
correct hosting environment.

📝 feat(firebase): update production app name

---

.gitignore

Adds the .firebase/* directory to the .gitignore file to
exclude it from version control. This is necessary as the
.firebase directory is used by the Firebase CLI to store
temporary files and should not be checked into the
repository.

✨ feat: Add .firebase/* to .gitignore

---

firebase.json
pubspec.yaml

- Bumps the version of the application to `1.0.4`
- Updates the cache headers to improve performance and caching for users
- The previous version had some issues with caching that we wanted to address
- Releasing a new version with the updated cache headers will provide a better user experience
- Tested the new cache headers locally and verified they are working as expected
- Ran all existing tests and they all passed

feat: Bump version to 1.0.4 and update cache headers

---

lib/controllers/student_barcode_controller.dart
lib/main.dart
lib/screens/students_in_exam_room/students_in_exam_room_screen.dart
pubspec.lock
pubspec.yaml

This commit introduces the use of the `worker_manager` package to handle
asynchronous tasks in the `StudentsInExamRoomController`. The changes are:
- Wrap the `getAllStudentsInExamRoom()` and `getStudents()` methods in
`workerManager.execute()` blocks to execute them asynchronously on a
separate worker thread.
- Update the `main()` function to initialize the `workerManager` before
running the app.
- Add the `worker_manager` package to the project's dependencies in the
`pubspec.yaml` file.
These changes aim to improve the app's performance and responsiveness by
offloading long-running network requests and other time-consuming operations
to a separate worker thread, preventing the main UI thread from being blocked.

✨ feat: Implement worker manager for asynchronous tasks

---

lib/controllers/profile_controller.dart
lib/services/token_service.dart

- Persist the cached user profile in the `saveProfileToHiveBox` method
- Simplify the `saveNewAccessToken` method by removing the `async` keyword
since the method no longer needs to await any asynchronous operations

✨ feat: Improve profile and token management

---

lib/controllers/profile_controller.dart

This change updates the `saveProfileToHiveBox()` method in the `ProfileController`
to first assign the `cachedUserProfile` to the `_cachedUserProfile` property before
saving it to the Hive box. This ensures that the `update()` method is called after
the profile has been updated, triggering a rebuild of the UI widgets that depend
on this controller.

🔖 feat(profile): Update cached user profile in Hive

---

lib/controllers/profile_controller.dart

Remove unnecessary update call after saving user profile to Hive.
This optimization avoids an unnecessary state update and improves
the overall performance of the ProfileController.

✨ feat(profile_controller): Update cached profile and save to Hive

---

pubspec.yaml

- Bumped the version in the `pubspec.yaml` file to `1.1.9`.
This change updates the version of the application to the latest release, `1.1.9`. This ensures that the application is up-to-date with the latest features and bug fixes.
To verify the changes, please check the updated `pubspec.yaml` file to confirm that the version has been correctly updated to `1.1.9`.

🔬 feat(version): Bump version to 1.1.9 in pubspec.yaml

---

lib/main_app.dart
pubspec.yaml

This commit updates the version number in the `pubspec.yaml` file from 1.1.10 to 1.1.11. This change is necessary to reflect the latest version of the application.
Additionally, this commit adds a new route handling for the `unknown` route, which will redirect the user to the `LoginForm` screen. This change ensures that if the user navigates to an unknown route, they are seamlessly redirected to the login screen, providing a better user experience.

🔌 feat(version): Increase version to 1.1.11

---

web/index.html

Replaces the hard-coded base href with an environment variable
`$FLUTTER_BASE_HREF`, allowing for more flexible deployment
configurations.

🎨 feat(web/index.html): Update base href with environment variable

---

lib/screens/students_in_exam_room/students_in_exam_room_screen.dart

Allows passing a function to `Get.to()` instead of a widget instance to
support late initialization of the `SimpleBarcodeScannerPage` widget.
This ensures that the controller is properly initialized before the
widget is displayed, preventing potential race conditions.

🔒 feat: Improve student QR code scanning

---

pubspec.lock
pubspec.yaml

The changes in this commit are focused on removing unused dependencies from the `pubspec.yaml` and `pubspec.lock` files. Specifically, the `socket_io_client` and `simple_barcode_scanner` packages have been removed, along with their transitive dependencies, as they are no longer needed by the application.
This cleanup helps to reduce the overall size of the application and improve its performance by removing unnecessary code and dependencies.

feat(pubspec): Remove unused dependencies

---

lib/services/students_in_exam_room_service.dart

The changes made in this commit address the handling of the `selectedExamMissionId` property in the `StudentsInExamRoomService` class. Previously, the `selectedExamMissionId` was stored as a single `int` value in the Hive box. However, this approach was not suitable, as a student can be assigned to multiple exam missions.
The main changes are:
- The `getFromHiveBox()` method now retrieves the `selectedExamMissionId` as a `List<dynamic>` and converts it to a `List<int?>`.
- The `setSelectedExamMissionId()` method now accepts a `List<int>` instead of a single `int`.
- The `setSelectedExamRoomAndExamMissionId()` method now accepts a `List<int?>` for the `examMissionIds` parameter.
These changes ensure that the `StudentsInExamRoomService` can handle multiple exam missions associated with a …

♻️ refactor(students_in_exam_room_service): handle selectedExamMissionId as a list

---

lib/resource_manager/ReusableWidget/my_text_form_field.dart
lib/screens/login_form.dart

This pull request adds the `autofillHints` parameter to the `MyTextFormField` widget. This parameter allows users to provide a list of autofill hints, which can help improve the user experience when filling out forms on mobile devices.
Additionally, this PR adds autofill hints for the username and password fields in the login form. This feature makes it easier for users to quickly fill in their login credentials, further enhancing the overall user experience.
1. Implemented the `autofillHints` parameter in the `MyTextFormField` widget.
2. Added autofill hints for the username and password fields in the login form.
- Improved user experience when filling out forms on mobile devices.
- Easier and faster login process for users.
- Consistent autofill behavior across the application.

add-autofill-hints

---

lib/screens/students_in_exam_room/students_in_exam_room_screen.dart

The changes in this commit focus on improving the display of student attendance status in the "StudentsInExamRoomScreen" widget. The key changes are:
- The background color of the student barcode widget is now determined by whether the student is selected or not, instead of their attendance status or cheating status.
- Selected students are displayed with a green background, while non-selected students are displayed with a red background.
- This change simplifies the logic and provides a more intuitive visual representation of the student's attendance status.

🎨 feat(students_in_exam_room): Enhance student attendance status display
